### ISSUE TITLE
Gulp Integration

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#140]
I've been dropping hints about this on the last couple of Designer calls. I spent the weekend playing with Gulp for a personal client, and I really quite like it. My goal is to set up wd_s with Gulp while retaining the workflow. Maybe it would even neat to offer both a Grunt and Gulp build options?

Will demo on the next call. 

**Todo:**
- [x] PostCSS (for Autoprefixer and MQ Packer support)
- [x] Combine Media Queries
- [x] Sourcemap on minified styles
- [x] Makepot (i18n support)
- [x] SassDocs
- [x] Notification (Growl) support on failures 
- [x] Move Bourbon/Neat out of Bower and into NPM
- [x] Ensure "Clean" is working correctly 
- [x] SVGstore is adding HTML headers into svg-icons.def (this is bad)
- [x] Recreate tasks like "styles, javascript, sprites" where applicable
- [x] BrowserSync... how can we make this as awesome as possible?

Would also like to see examples of how others are using Gulp and their config files...

**Comment by efuller** [comment]
+1 for this! Hopefully in the process, it will fix our sourcemap issues.

**Comment by gregrickaby** [comment]
I've pushed up my initial Gulp set up in a feature branch. I'd love to have everyone play with it and post feedback here. Check it out!

https://github.com/WebDevStudios/wd_s/tree/feature/gulp

**Comment by stacyk** [comment]
Super excited about this. I was going to move everything over to gulp too and poof, you did it for me :) Can't wait to play!

**Comment by gregrickaby** [comment]
To do:

- Autoprefixer
- Combine Media Queries
- Sourcemap on minified styles
- Makepot (i18n support)
- SassDocs
- Notification (Growl) support on failures

**Comment by allisonplus** [comment]
I've been playing around for notifications and this is where I am currently.

``` javascript
// Add to list
var notify= require('gulp-notify');
```

``` javascript
// Compile Sass and create stylesheet.
gulp.task('sass', function() {
    return gulp.src('assets/sass/*.scss')

    .pipe(sourcemaps.init())
        .pipe(sass({
            includePaths: neat,
            outputStyle: 'expanded'
        }))
    .on('error', handleErrors)
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('./'));
});
```

``` javascript
//Growl Notification for Errors
function handleErrors() {
    var args = Array.prototype.slice.call(arguments);
    notify.onError({
        title: 'Compile Error',
        message: '<%= error.message %>'
    }).apply(this, args);
    this.emit('end'); // Keeps it from hanging on the task
}
```

**Comment by gregrickaby** [comment]
I'm at a really good place with the Gulpfile. I feel like it's nearly development ready.
- Icons, Scripts, Sprites, and Styles work!
- i18n is being weird and isn't scanning PHP files even though I have it configured properly.
- I have not integrated Gulp Notify yet.

**Changes:**
https://github.com/WebDevStudios/wd_s/commit/100394ab8edd294bdff554b0a2db6543eba8abe2#diff-878989239e07228f7903fde98f450ed9

**Full file:**
https://github.com/WebDevStudios/wd_s/blob/100394ab8edd294bdff554b0a2db6543eba8abe2/Gulpfile.js

**To test:**
- Checkout `/feature/gulp`
-  `npm install`
- `gulp watch`

**Comment by JPry** [comment]
I'm going to attempt to work on the makepot portion.

**Comment by JPry** [comment]
Makepot is working! Here is the link to the changes that I added: https://github.com/WebDevStudios/wd_s/compare/6bc32dfd1d05051fae8e267b5690ed91b2f2375f...be4e1812696c2a0b908e7418ff33b1cf549c873e (updated)

**Comment by JPry** [comment]
We may be able to use `gulp-notify` for Notifications: https://github.com/mikaelbr/gulp-notify. I started to look into it and it seems like it would do what we need.

**Comment by gregrickaby** [comment]
Update: 

Currently at a stand-still until https://github.com/thoughtbot/neat/pull/397 is merged in. This will allow us to drop both Bourbon/Neat from Bower and use them as NPM packages instead.

Growl notifications on error are still under development. Thanks to @allisonplus for helping me with that and @JPry for getting Makepot working.

**Comment by colorful-tones** [comment]
I added error handling monkey-patch with gulp-plumber, gulp-util, and gulp-notify. Tested, and works with failed Sass and JS compilations. Can't wait for Gulp 4.0 with error built in. 🦄

Associated commits:
- [add gulp-util to package.json](https://github.com/WebDevStudios/wd_s/commit/c0f220be92e57ec03bb5d327ba7f62dc31735550)
- [set var gutil = require('gulp-util')](https://github.com/WebDevStudios/wd_s/commit/c52984dfedd16bd63ff719e1f5f94523b60eb9e1)
- [set var notify = require('gulp-notify')](https://github.com/WebDevStudios/wd_s/commit/044b23a68902796436a5fa6b828a034b48a13f9b)
- [add handleErrors function to Gulpfile.js](https://github.com/WebDevStudios/wd_s/commit/ff58e6c5029e696d2cbf27f4400b8b7237390efd)
- [replace .on('error) events with .pipe(plumber({errorHandler:handleErr…](https://github.com/WebDevStudios/wd_s/commit/3c3158a7871143c20d793b8e9b8b82ce73078aec)

**Comment by gregrickaby** [comment]
Putting this through it's paces on a personal client and I've found the following things:
- [x] Remove all previous error handling code from Gulpfile.js
- [x] Svgmin isn't remove stroke/fill 
- [x] SVG template tag is calling .icon-svg-name instead of just .svg-name
- [x] CSS that targets SVGs will need to be updated
- [x] Rename scripts.js to project.js inside scripts.php
- [x] BrowserSync isn't proxying correctly. I see the site on localhost:3000, but isn't connecting when I type my actual local ".dev" address

**Comment by gregrickaby** [comment]
Ok, all the above issues have been checked off (including all original requirements). I've spent the last hour trying to break it, and now everything is working as expected with these commits: https://github.com/WebDevStudios/wd_s/compare/2aaf82ba709c...e72580691a6c

IMHO: Gulp is ready to be merged in, as soon as https://github.com/thoughtbot/neat/pull/397 is merged into https://github.com/thoughtbot/neat.

Thanks to @allisonplus @colorful-tones @JPry and @efuller for all the help. :heart: y'all!

**Comment by gregrickaby** [comment]
Good news! https://github.com/thoughtbot/neat/pull/397 has been merged in. I'm told that they will have an update to NPM early next week. Once this drops, we'll be ready to merge this in.

**Comment by colorful-tones** [comment]
[![selfie-3](http://i.imgur.com/8s2n8xa.gif)](https://github.com/thieman/github-selfies/)
